# Generated by Django 4.2.28 on 2026-06-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional: photo or scan of a handwritten prescription, lab result, or referral (JPG, PNG, or PDF).', null=True, upload_to='prescriptions/%Y/%m/'),
        ),
    ]
