# Generated by Django 4.2.28 on 2026-07-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_patientprofile_middle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short professional bio shown on your public doctor profile.'),
        ),
    ]
